spring:
  application:
    name: service-finance
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/contractmgn?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: wuhanquan

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
  instance:
      prefer-ip-address: true

server:
  port: 8084

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  mapperLocations: classpath:mapping/*.xml
  configuration:
      map-underscore-to-camel-case: true
