spring:
  application:
    name: service-schedule
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.103.10.9:3306/contractmgn?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: false
  instance:
      prefer-ip-address: true

server:
  port: 8081

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
