spring:
  application:
    name: service-gateway
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.103.10.9:3306/contractmgn?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

mybatis:
  mapperLocations: classpath:mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
      prefer-ip-address: true

server:
  port: 8080

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

pdf:
  path: /Users/songzixiao/Desktop/pdf/

tmp:
  dir: /Users/songzixiao/Desktop/pdf/

